### ISSUE TITLE
onConflictUpdate() does not apply database-level column naming convention

### ISSUE THREAD

**Issue by aboisvert** [com-lihaoyi/scalasql#18]
Here is a relevant stacktrace:

```
[error] org.postgresql.util.PSQLException: ERROR: column "athleteid" does not exist
[error]   Hint: Perhaps you meant to reference the column "recruit_rosters.athlete_id" or the column "excluded.athlete_id".
[error]   Position: 158
[error] 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
[error] 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
[error] 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
[error] 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
[error] 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
[error] 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
[error] 	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
[error] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[error] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[error] 	at scalasql.core.DbApi$.scalasql$core$DbApi$Impl$$_$runRawUpdate0$$anonfun$3(DbApi.scala:456)
[error] 	at scalasql.core.DbApi$Impl.configureRunCloseStatement(DbApi.scala:504)
[error] 	at scalasql.core.DbApi$Impl.runRawUpdate0(DbApi.scala:456)
[error] 	at scalasql.core.DbApi$Impl.updateSql(DbApi.scala:284)
[error] 	at scalasql.core.DbApi$Impl.run(DbApi.scala:203)
[error] 	at fanstake.datasync.RecruitsLoader$.insertOrUpdateRecruitRosters$$anonfun$1(RecruitsLoader.scala:307)
```

Note that column `athleteid` should actually be `athlete_id`.  This field `athleteId` (as it is named in the case class) is properly converted to *snake_case* in other queries, just not in the `ON CONFLICT` clause.

Here's the relevant part of the code:

```scala
        RecruitRosters.insert
          .columns(
            _.athleteId := r.athleteId,
            _.seasonId := r.seasonId,
            _.teamId := r.teamId,
            _.recruitingStatus := r.recruitingStatus,
            _.recruitingStatusDate := r.recruitingStatusDate,
            _.details := r.details
          )
          .onConflictUpdate(_.athleteId, _.seasonId)(
            _.teamId := r.teamId,
            _.recruitingStatus := r.recruitingStatus,
            _.recruitingStatusDate := r.recruitingStatusDate,
            _.details := r.details
          )
```

**Comment by aboisvert** [comment]
From a cursory look, it appears `OnConflict.renderSql()` needs to pass column names through `config.columnNameMapper`

**Comment by lihaoyi** [comment]
Sounds reasonable. Could you open a pull request? You can test it locally by running `./mill -i __.publishLocal` to get a version you can try out on your machine to verify it fixes the issue

**Comment by aboisvert** [comment]
@lihaoyi I created a PR that fixes my issue and passes all the tests.  Do you have a suggestion with respect to adding a test that specifically tests the issue?  It would necessitate adding a new table with at least one kebab_case primary key.

**Comment by lihaoyi** [comment]
I think we're fine merging as is.

**Comment by lihaoyi** [comment]
The main thing is that adding a regression test for this case would not prevent other bugs in this class of issue in other APIs, duplicating all the tests to cover name mapping would be unfeasible, and adding name mapping to all the existing tests may be distracting in the documentation. There's probably a way forward, but for now I think we can just go with the fix since you've tested it manually

**Comment by lihaoyi** [comment]
0.1.5 should be out with your fix
